[package]
name = "vertex_clustering"
version = "0.1.0"
edition = "2021"
description = "A simple implementation of vertex clustering."
license = "MIT OR Apache-2.0"

[dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
